name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

concurrency:
  # group runs by <name of the workflow>-<name of job>-<branch name>
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Check linting
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Review linting
        run: pnpm lint
